Deli_Inventory/Models/CurrentProduct.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Deli_Inventory.Models
{
    public class CurrentProduct
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public DateTime ExpireDate  { get; set; }
        public string WhoPutOut { get; set; }
    }
}

Deli_Inventory/Models/ErrorViewModel.cs
using System;

namespace Deli_Inventory.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Deli_Inventory/Controllers/CurrentProductController.cs
using Deli_Inventory.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Deli_Inventory.Controllers
{
    public class CurrentProductController : Controller
    {
        private readonly ICurrentProduct repo;

        public CurrentProductController(ICurrentProduct repo)
        {
            this.repo = repo;
        }

        //GET: /<controller>/
        public IActionResult Index()
        {
            var products = repo.GetAllProducts();
            return View(products);
        }
        public IActionResult ViewCurrentProduct(int id)
        {
            var product = repo.GetProduct(id);

            return View(product);
        }

        public IActionResult UpdateCurrentProduct(int id)
        {
            CurrentProduct prod = repo.GetProduct(id);

            if (prod == null)
            {
                return View("ProductNotFound");
            }

            return View(prod);
        }

        public IActionResult UpdateCuProductToDatabase(CurrentProduct product)
        {
            repo.UpdateCurrentProduct(product);

            return RedirectToAction("ViewCurrentProduct", new { id = product.Id });
        }





    }
}

Deli_Inventory/Controllers/HomeController.cs
using Deli_Inventory.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Deli_Inventory.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Deli_Inventory/Views/CurrentProduct/Index.cshtml
@model IEnumerable<CurrentProduct>

    <h2>Products</h2>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>ItemName</th>
            <th>ExpireDate</th>
            <th>WhoPutOut</th>
        </tr>

        @foreach (var product in Model)
            {
                <tr>
                    <td><a href=/CurrentProduct/ViewCurrentProduct/@product.Id>@product.Id</a></td>
                    <td>@product.ItemName</td>
                    <td>@product.ExpireDate</td>
                    <td>@product.WhoPutOut</td>
                </tr>

            }
    </table>

Deli_Inventory/Views/CurrentProduct/UpdateCurrentProduct.cshtml
@model CurrentProduct

<h2>Update @Model.ItemName</h2>

@using (Html.BeginForm("UpdateProductToDatabase", "Product", "Post"))
{
    <input asp-for="ItemName" type="hidden" value="@Model.ItemName" />

    <label asp-for="ItemName" class="control-label">ItemName</label>

    <input type="text" name="ExpireDate" class="form-control" value="@Model.ExpireDate" />

    <label asp-for="WhoPutOut" class="control-label">WhoPutOut</label>

    <input type="number" step="0.01" name="WhoPutOut" class="form-control" value="@Model.WhoPutOut" />

    <input type="submit" value="Update Product" class="btn btn-primary" />

}

Deli_Inventory/Views/CurrentProduct/ViewCurrentProduct.cshtml
@model CurrentProduct

<h3>@Model.ItemName Information</h3>

<table class="table">
    <tr>
        <th>ItemName</th>
        <th>ExpireDate</th>
        <th>WhoPutOut</th>
    </tr>
    <tr>
        <td>@Model.Id</td>
        <td>@Model.ItemName</td>
        <td>@Model.ExpireDate</td>
        <td>@Model.WhoPutOut</td>
    </tr>

</table>

<div style="display: block">
    <a href="/Product/UpdateProduct/@Model.Id">Update this Product</a>
</div>

Deli_Inventory/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Deli_Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Deli_Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Deli_Inventory</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CurrentProduct" asp-action="Index">Current Products
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Deli_Inventory - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>